package view;
import dao.ProdutoDAO;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;
/**
 *
 * @author cadu
 */
public class Produtos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Produtos.class.getName());
    private java.util.ArrayList<model.Produto> listaProdutos =
        new java.util.ArrayList<>();
    

private int proximoId = 1;
private int idProdutoEditando = -1;
    /**
     * Creates new form Produtos
     */
    public Produtos() {
    initComponents();
    atualizarTabela();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        lblCategoria = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabelaProdutos = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnEcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 102, 0));
        lblTitulo.setText("CADASTRO DE PRODUTOS");

        jLabel1.setText("Nome do Produto:");

        txtNome.addActionListener(this::txtNomeActionPerformed);

        lblPreco.setText("Preço:");

        txtPreco.addActionListener(this::txtPrecoActionPerformed);

        lblQuantidade.setText("Quantidade:");

        txtQuantidade.addActionListener(this::txtQuantidadeActionPerformed);

        btnLimpar.setFont(new java.awt.Font("Bitstream Charter", 3, 18)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.setPreferredSize(new java.awt.Dimension(180, 40));
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        btnVoltar.setFont(new java.awt.Font("Bitstream Charter", 3, 18)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setPreferredSize(new java.awt.Dimension(180, 40));
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        btnCadastrar.setFont(new java.awt.Font("Bitstream Charter", 3, 18)); // NOI18N
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.setPreferredSize(new java.awt.Dimension(180, 40));
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        lblCategoria.setText("Categoria:");

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipamentos Táticos", "Airsoft", "Camping", "Sobrevivência", "Vestuário", "Acessórios" }));
        cbCategoria.addActionListener(this::cbCategoriaActionPerformed);

        tblTabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Categoria", "Preço", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(tblTabelaProdutos);

        btnEditar.setFont(new java.awt.Font("Bitstream Charter", 3, 18)); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnEcluir.setFont(new java.awt.Font("Bitstream Charter", 3, 18)); // NOI18N
        btnEcluir.setText("EXCLUIR");
        btnEcluir.setToolTipText("");
        btnEcluir.addActionListener(this::btnEcluirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPreco)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuantidade)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria)
                            .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnEcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTitulo)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblPreco)
                        .addGap(6, 6, 6)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblQuantidade)
                        .addGap(6, 6, 6)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblCategoria)
                        .addGap(6, 6, 6)
                        .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // oque o botao limpar deve fazer
        txtNome.setText("");
txtPreco.setText("");
txtQuantidade.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // oque o botao cadastrar deve fazer
    try {

        String nome = txtNome.getText();

        double preco = Double.parseDouble(
                txtPreco.getText().replace(",", ".")
        );

        int quantidade = Integer.parseInt(
                txtQuantidade.getText()
        );

        String categoria =
                cbCategoria.getSelectedItem().toString();

        String observacoes = "";

        int idFornecedor = 0;

        Produto produto = new Produto(
                nome,
                preco,
                quantidade,
                categoria,
                observacoes,
                idFornecedor
        );

        ProdutoDAO dao = new ProdutoDAO();

        // ================= ALTERAÇÃO =================

        if (idProdutoEditando != -1) {

            produto.setId(idProdutoEditando);

            dao.alterar(produto);

            JOptionPane.showMessageDialog(
                    this,
                    "Produto alterado com sucesso!"
            );

            idProdutoEditando = -1;

        } else {

            // ================= CADASTRO =================

            dao.cadastrar(produto);

            JOptionPane.showMessageDialog(
                    this,
                    "Produto cadastrado com sucesso!"
            );
        }

        // Limpa os campos
        txtNome.setText("");
        txtPreco.setText("");
        txtQuantidade.setText("");

        // Atualiza a tabela
        atualizarTabela();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Preço ou quantidade inválidos!"
        );

    } catch (java.sql.SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Erro ao salvar produto no banco de dados:\n"
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // oque o botao voltar deve fazer
        MenuPrincipal menu = new MenuPrincipal();

menu.setVisible(true);

this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void btnEcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEcluirActionPerformed
        // TODO add your handling code here:
int linha = tblTabelaProdutos.getSelectedRow();

    if (linha == -1) {

        JOptionPane.showMessageDialog(this,
                "Selecione um produto para excluir.");

        return;
    }

    int id = Integer.parseInt(
            tblTabelaProdutos.getValueAt(linha, 0).toString()
    );

    int confirmacao = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente excluir este produto?",
            "Confirmar exclusão",
            JOptionPane.YES_NO_OPTION
    );

    if (confirmacao != JOptionPane.YES_OPTION) {
        return;
    }

    try {

        ProdutoDAO dao = new ProdutoDAO();

        dao.excluir(id);

        JOptionPane.showMessageDialog(
                this,
                "Produto excluído com sucesso!"
        );

        atualizarTabela();

    } catch (java.sql.SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Erro ao excluir produto:\n" + e.getMessage()
        );
}

listaProdutos.remove(linha);

atualizarTabela();

JOptionPane.showMessageDialog(this,
        "Produto excluído com sucesso!");
    }//GEN-LAST:event_btnEcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // oque o botao editar deve fazer
     int linha = tblTabelaProdutos.getSelectedRow();

    if (linha == -1) {

        JOptionPane.showMessageDialog(
                this,
                "Selecione um produto para editar."
        );

        return;
    }

    // Pega o ID do produto selecionado
    idProdutoEditando = Integer.parseInt(
            tblTabelaProdutos.getValueAt(linha, 0).toString()
    );

    // Pega os dados da tabela
    String nome =
            tblTabelaProdutos.getValueAt(linha, 1).toString();

    String categoria =
            tblTabelaProdutos.getValueAt(linha, 2).toString();

    String preco =
            tblTabelaProdutos.getValueAt(linha, 3).toString();

    String quantidade =
            tblTabelaProdutos.getValueAt(linha, 4).toString();

    // Coloca os dados nos campos
    txtNome.setText(nome);
    txtPreco.setText(preco);
    txtQuantidade.setText(quantidade);

    cbCategoria.setSelectedItem(categoria);

    JOptionPane.showMessageDialog(
            this,
            "Produto carregado para edição.\n"
            + "Altere os dados e clique em CADASTRAR para salvar."
    );
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Produtos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEcluir;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblTabelaProdutos;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabela() {

    DefaultTableModel modelo =
            (DefaultTableModel) tblTabelaProdutos.getModel();

    modelo.setRowCount(0);

    try {

        ProdutoDAO dao = new ProdutoDAO();

        java.util.List<Produto> produtos = dao.listarTodos();

        for (Produto p : produtos) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getCategoria(),
                p.getPreco(),
                p.getQuantidade()
            });
        }

    } catch (java.sql.SQLException e) {

        JOptionPane.showMessageDialog(this,
                "Erro ao carregar produtos do banco de dados:\n"
                + e.getMessage());
    }

}
}
